mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import handler404
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('polls.urls')),#ta sẽ liên cái web với nhau hiểu đơn giản cta liên cái project mysite với cái web sever bằng cái url 
    #nếu path('polls' thì hiểu đơn giản urls của app polls sẽ do áp pollsquar lý muốn vào nó thì phải qua polls còn nếu dể '' ntn thfi nó chạy thằng tới hàm index trg views 
    path('Blogpost/', include('Blogpost.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/polls/urls.py
from django.urls import path  # cái path này dùng để định nghĩ các url
from . import views
from django.urls import path, include
from django.conf.urls import handler404,url
from django.contrib.auth import views as auth_views

urlpatterns = [
    # path là  đường dẫn trắng chính là xử lý cho urls http://localhost:8000/polls
    path('', views.home),
    path('contact/', views.contact, name='contact'),
    path('ContactComment/', views.ContactComment, name='ContactComment'),

    path('home/', views.home, name='home'),
    path('polls/', views.polls, name='polls'),
    path('Blogpost/', include('Blogpost.urls')),
    path('register/', views.register, name="register"),
    path('login/', auth_views.LoginView.as_view(template_name="pages/login.html"), name="login"),
    path('logout/', auth_views.LogoutView.as_view(next_page='/polls'), name='logout'),
]

handler404 = 'polls.views.error'

mysite/polls/models.py
from django.db import models
from django.conf import settings



# như này đầu tiên mình tạo class xong mình phải makemigrations nó để liên kết với bản xong đó migrate để cập nhật nó 

# sau đó python manage.py makemigrations polls để báo với sql là ta vừa tạo 1 cái poll 
# sau đó ta sd python manage.py migrate để cập nhật

class Comment(models.Model):
    
#   <class 'polls.admin.CommentInline'>: (admin.E202) 'polls.Commenttt' has no ForeignKey to 'polls.Poll'.
    # comment = models.ForeignKey(Comment, on_delete=models.CASCADE, related_name='comments')

    # ta khai báo field post là khóa ngoại liên kết với bảng Post, tham số on_delete Kteam cho nó thuộc loại CASCADE (có nghĩa là khi xóa bài viết thì xóa luôn bình luận), tham số related_name có nghĩa khi dev muốn tìm các bình luận từ một bài viết thì thông qua từ khóa ‘comments’ từ post
    # NameAcc = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    # tương tự author là khóa ngoại liên kết bảng user của hệ thống Django để biết ai là người bình luận bài viết.
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
class Commenttt(models.Model):
    # commenttt = models.ForeignKey(Comment, on_delete=models.CASCADE, related_name='comments')
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)

mysite/polls/forms.py
from django import forms
from django import forms
import re
from django.contrib.auth.models import User
from .models import Comment, Commenttt


class RegistrationForm(forms.Form):

    username = forms.CharField(label='username',  max_length=30)
    email = forms.EmailField(label='email')
    password1 = forms.CharField(label='password', widget=forms.PasswordInput())
    password2 = forms.CharField(
        label='Re-password', widget=forms.PasswordInput())

    def clean_password2(self):
        if 'password1' in self.cleaned_data:
            password1 = self.cleaned_data['password1']
            password2 = self.cleaned_data['password2']
            if password1 == password2 and password1:
                return password2
        raise forms.ValidationError("Invalid password")

    def clean_username(self):
        username = self.cleaned_data['username']
        if re.search(r'^\w+&', username):
            raise forms.ValidationError("Invalid username")
        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username
        raise forms.ValidationError("Account already exists")

    def save(self):
        User.objects.create_user(
            username=self.cleaned_data['username'], email=self.cleaned_data['email'], password=self.cleaned_data['password1'])


class CommentCreateForm(forms.ModelForm):

   
    class Meta:
        model = Comment
        fields = ('body',)
        # (tên tác giả và bài viết được comment không thể nhập tay được) nên khai báo fields chỉ có body để form chỉ tạo input body. tức ta chỉ hiện đc nd của nó thôi 


class CommentttCreateForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        # Kteam override phương thức khởi tạo, mục đích là lấy giá trị author và post để lưu vào bảng comment. Sau khi lấy xong thì ta gọi tiếp phương thức khởi tạo của class cha.
        self.author = kwargs.pop('author', None)
        # self.post = kwargs.pop('post', None)
        super().__init__(*args, **kwargs)
    def save(self, commit=True):
        # Kteam override phương thức save có sẵn của ModelForm, việc override này mục đích gán giá trị author và post. Đầu tiên là gọi phương thức save của class cha (ta cho tham số commit = False để chưa lưu xuống database). Sau đó lấy instance comment ra và gán giá trị author và post rồi mới gọi phương thức save() của model.
        # tham số commit = False để chưa lưu xuống database
        comment = super().save(commit=False)
        comment.author = self.author
        # comment.post = self.post
        comment.save()

    class Meta:
        model = Commenttt
        fields = ('body',)
        # (tên tác giả và bài viết được comment không thể nhập tay được) nên khai báo fields chỉ có body để form chỉ tạo input body. tức ta chỉ hiện đc nd của nó thôi 

mysite/polls/views.py
from .forms import RegistrationForm
from django.views.decorators.http import require_POST
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponseRedirect
# Create your views here.
from django.http import HttpResponse

from .forms import CommentCreateForm, CommentttCreateForm
from .models import Comment, Commenttt


# def polls(request):
#    return render(request, 'pages/polls.html')

# def contact(request):
#    return render(request,"pages/contact.html")


def home(request):
   return render(request, "pages/home.html")


def error(request, exception):
    return render(request, 'pages/error.html', {'message': exception})


def register(request):
    form = RegistrationForm()
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/')
    return render(request, 'pages/register.html', {'form': form})


def polls(request):

    form = CommentttCreateForm()
    if request.method == "POST":
        form = CommentttCreateForm(request.POST, author=request.user)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(request.path)
    context = {
        'Commenttt_list': Commenttt.objects.all(),
        'form': CommentttCreateForm(),
    }
    return render(request, 'pages/polls.html', context)


def contact(request):

    form = CommentCreateForm()
    if request.method == "POST":
        form = CommentCreateForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(request.path)
    context = {
        'Comment_list': Comment.objects.all(),
        'form': CommentCreateForm(),
    }
    return render(request, "pages/contact.html", context)


def ContactComment(request):
    form = CommentCreateForm()
    # nó sẽ gọi cái from rồi nếu method post( action="{% url 'ContactComment' %}" method="POST") thì nó chạy vào save r return  
    if request.method == "POST":
        form = CommentCreateForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(request.path)
    return render(request, "pages/ContactComment.html")

mysite/polls/templates/pages/ContactComment.html
{% load static %}
   <link rel="stylesheet" href="{% static 'css/comment.css' %}">
{% comment %} <body style="margin:0;background:#dadce0"> {% endcomment %}
    

{% comment %} <div style="background:#dadce0" class="comment"> {% endcomment %}
<body >
     <header >
         <img src="{% static './images/img-0376.jpg' %}" alt="" >
     </header>
{% comment %} <div  class="comment-content__header"></div> {% endcomment %}
      
     <div class="comment-content">
           <div class="comment-content__header"></div>
           <div class="comment-content__body">
                <p1>感想を書いていただき, ありがとうございました。</p1>
                <div class="comment-content__a">
                    <p2>もう一度ゲームを楽しみましょう！！！</p2>
                    <a  href="{% url 'contact' %}">ゲーム</a>
               
              
                </div>
                <div class="comment-content__a">
                 <a  href="{% url 'home' %}">Blog</a>
                </div>
               
            
            </div>    
           <footer>
               <span>江戸川大学ー情報文化学科―山口先生ゼミ</span>
            </footer>
     </div>
</body>
{% comment %} </div> {% endcomment %}
{% comment %} </body> {% endcomment %}

mysite/polls/templates/pages/contact.html
{% load static %}
<link
  rel="stylesheet"
  href="{% static 'css/contact3.css' %}
"
/>
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" />
<link
  rel="stylesheet"
  href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css"
/>

<body>
  <div class="flappBird">
    <div id="btnStart" class="btnStart">
      <div style="padding-top: 45%">
        <button id="btnClick" class="btnGame" onclick="btnClick()">
          START
        </button>
        <button id="btnScore" class="btnGame">SCORE</button>
      </div>
    </div>
    <div
      class="btnNext"
      id="btnNext"
      onclick="btnNext()"
      style="text-align: center; display: none"
    ></div>
    <div class="GameOver" id="GameOver" style="display: none">
      <div class="GameOver_bg">
        <img
          src="{% static 'images/over1.png' %}"
          style="
            padding-bottom: 25px;

            width: 75%;
            margin-left: 45px;
          "
          alt=""
        />
        <div class="score">
          <img
            src="{% static 'images/anhgif.gif' %}"
            style="width: 40%; padding: 20px"
            alt=""
          />
          <div class="GameOver_Score">
            <button id="btnScoree" class="btnGame" style="margin-bottom: 16px">
              SCORE:0
            </button>
            <br />
            <button id="btnGame_Again" class="btnGame">Again</button>
          </div>
        </div>
      </div>
    </div>

    <canvas id="canvas" width="900" height="500" style="display: none"></canvas>

    <nav
      class="nav justify-content: left;"
      style="flex-wrap: nowrap; margin-top: 20px"
    >
      <a class="nav-link">
        <img class="info_img" src="{% static 'images/bird2.jpg' %}" alt=""
      /></a>
      <a class="nav-link">
        <h4 class="info_title">Flappy Bird</h4>
        <p class="info_text">
          Flappy Birdは、ベトナム人の開発者グエン・ハー・ドン(Nguyen Ha
          Dong)氏によって、たった2,3日間で作成されたゲームで、米App
          Storeの無料アプリランキングで上位をキープし続け、ゲーム内のバナー広告の売上は一日で約510万円も売り出していたアプリである。
        </p></a
      >
    </nav>
    <h1>感想をお願い致します。</h1>
    <hr />

    <form action="" method="POST">
      {% csrf_token %}

      <div class="form_comment">
        <div class="form_user col-2">
          <i class="fa fa-user-tie"></i>
        </div>
        <input
          type="text"
          name="body"
          required=""
          id="id_body"
          placeholder="感想を書く..."
        />
      </div>
    </form>
    <div class="hienThiCmt">
      <div class="Cmt_user">
        <div class="form_user col-2" id="form_edo">
          <i class="fa fa-user-tie"></i>
        </div>
        <div class="Ctm_edo">
          <h2>江戸川大学</h2>
          <h6><p>2021年10月27日 4:01</p></h6>
          <p>よろしくお願いいたします。</p>
        </div>
      </div>
      {% for comment in Comment_list %}
      <div class="Cmt_user">
        <div class="form_user col-2">
          <i class="fa fa-user-graduate"></i>
        </div>
        <div class="Ctm_text">
          <h2>Student</h2>
          <h6><p>{{comment.date}}</p></h6>
          <p>{{comment.body|linebreaks}}</p>
        </div>
      </div>

      {% endfor %}
    </div>
  </div>

  <script>
    var canvas = document.getElementById("canvas");
    var context = canvas.getContext("2d");

    var birdimg = new Image();
    var hinhnenchinh = new Image();
    var fg = new Image();
    var ongtren = new Image();
    var ongduoi = new Image();

    var img = new Image();

    img.src = "{% static 'images/gameover.png' %}";

    birdimg.src = "{% static 'images/bird.png' %}";
    hinhnenchinh.src = "{% static 'images/nenchinh.png' %}";
    fg.src = "{% static 'images/fg1.png' %}";
    ongtren.src = "{% static 'images/ongtren.png' %}";
    ongduoi.src = "{% static 'images/ongduoi.png' %}";

    var fly = new Audio();
    var scor = new Audio();

    fly.src = "{% static 'sounds/fly.mp3' %}";
    scor.src = "{% static 'sounds/score.mp3' %}";

    var KhoangCachHaiOng = 100;
    var KhoangCachOngDuoi;
    var bX = 30;
    var bY = 150;

    var gravity = 1.5;

    var score = 0;

    var ong = [];
    ong[0] = {
      x: canvas.width,
      y: 0,
    };
    window.addEventListener("keydown", moveUp);
    function moveUp() {
      bY -= 30;
      fly.play();
    }
    function draw() {
      context.drawImage(hinhnenchinh, 0, 0);
      for (var i = 0; i < ong.length; i++) {
        KhoangCachOngDuoi = ongtren.height + KhoangCachHaiOng;
        context.drawImage(ongtren, ong[i].x, ong[i].y);
        context.drawImage(ongduoi, ong[i].x, ong[i].y + KhoangCachOngDuoi);

        ong[i].x -= 3;
        if (ong[i].x == canvas.width - 300) {
          ong.push({
            x: canvas.width,
            y: Math.floor(Math.random() * ongtren.height) - ongtren.height,
          });
        }
        if (
          bY <= 0 ||
          bY + birdimg.height >= canvas.height - fg.height ||
          (bX + birdimg.width >= ong[i].x &&
            bX <= ong[i].x + ongtren.width &&
            (bY <= ong[i].y + ongtren.height ||
              bY + birdimg.height >= ong[i].y + KhoangCachOngDuoi))
        ) {
          setTimeout(function () {
            window.addEventListener("keydown", moveUp);
            function moveUp() {
              fly.pause();
            }
            document.getElementById("GameOver").style.display = "block";
            document.getElementById("btnScoree").innerHTML = "Score: " + score;
            document.getElementById("btnScoree").onclick = function () {
              alert("あなたの点数　：" + score);
            };
            document.getElementById("btnGame_Again").onclick = function () {
              location.reload();
              // btnNext();
            };
          }, 500);
          return;
        }

        if (ong[i].x == 0) {
          score++;
          scor.play();
        }
      }

      context.drawImage(fg, 0, canvas.height - fg.height); //cái khung ở dưới x-0 còn y thì bằng cao của cvs trừ cái cao của khung
      context.drawImage(birdimg, bX, bY);
      bY += gravity;
      context.fillStyle = "#000";
      context.font = "20px Verdana";
      context.fillText("Score : " + score, 10, canvas.height - 20);
      requestAnimationFrame(draw);
    }

    document.getElementById("btnScore").onclick = function () {
      alert("STARTのボタンをクリックしてゲームをしましょう");
    };
    function btnClick() {
      document.getElementById("btnNext").style.display = "block";
      document.getElementById("btnStart").style.display = "none";
      fly.play();
    }
    function btnNext() {
      document.getElementById("canvas").style.display = "block";
      document.getElementById("btnNext").style.display = "none";

      fly.play();

      draw();
    }
  </script>
</body>

mysite/polls/templates/pages/error.html
{% extends "pages/index.html" %}
 
{% block title %}Error{% endblock %}
 
{% block content %}
<h3>{{message}}</h3>
{% endblock %}

mysite/polls/templates/pages/home.html
{% extends "pages/index.html" %}
{% load static %}
{% block title %}
Home
{% endblock %}

{% block content %}
<div class="home">
       <div class="row">
        <h1>ベトナムの絶景を見に行こう！</h1>
            <img src="{% static './images/ha.jpg' %}"alt="" style="width:100%;" >
            <p>料理やフランス統治時代の影響を残す街並み、雑貨やカフェにも引かれるベトナムですが、今回は他では見ることのできない大自然の絶景を、定番から秘境に至るまでご紹介します。</p>
            <h1>定番だけど外せない！龍の伝説ハロン湾</h1>
            <img src="{% static './images/hb.jpg' %}"alt="" style="width:100%;" >
            <p>言わずとしれたベトナムの名所であり世界自然遺産のハロン湾。人気の観光地ですので、数多く用意されているツアーにはクルーズやカヤック体験、洞窟マーケット見学、さらにライトアップされた鍾乳洞を巡るコースもあり、いろんな角度から美しい景色を堪能することができます。</p>
            <h1>ベトナムと中国の国境近くにある神秘の滝！バンゾック滝</h1>
            <img src="{% static './images/hc.jpg' %}"alt="" style="width:100%;" >
            <p>全長300m高さ50mというベトナム最大級の滝です。中国との国境がある山間部に位置し、到達するのに時間を要する秘境ですが、旅の疲れも忘れるほど壮大なスケールの自然が待っています。雨量の増す夏は特に見応えがあり、滝に虹がかかることもあります。夕焼けも神秘的で、自然の壮大さに感動する人が後を絶ちません。</p>

 
    </div>
</div>



{% endblock %}

mysite/polls/templates/pages/index.html
<!DOCTYPE html>
<html lang="en">
<head>
{% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
     <link rel="stylesheet" href="{%static 'css/bootstrap.min.css' %}" type="text/css">
     <link rel="stylesheet" href="{% static 'css/indexy.css' %}">

   
</head>
<body>
   <header>
        <div class="header_img">
            <!-- <img src="./images/laco.png" alt="" width="100%" height="300"> -->
        </div>

        <div class="header_title">
            <div class="row">
               <div class="header_left col-sm-6 　">


                   <div class="header_left--title ">
                      <h1> グエン　タントゥ </h1>
                      <p>ベトナム風景を紹介するブログ</p>
                    </div>
                </div>
                <div class="header-right  col-sm-6">

                   <ul class="nav">
                    <li class="nav-item">
                        <img src="{% static './images/vietnhat.jpg' %}" alt="">

                        {% comment %} <img src="./images/vietnhat.jpg" alt=""> {% endcomment %}

                    </li>
                    <li class="nav-item">
                         <img src="{% static './images/halong1.jpg' %}" alt="">
                  

                    </li>
                    <li class="nav-item">
                        <img src="{% static './images/hue.jpg' %}" alt="">

                     

                    </li>
                    <li class="nav-item">
                        <img src="{% static './images/duater.jpg' %}" alt="">

                      

                    </li>

                    <li class="nav-item">
                         <img src="{% static './images/nhatrang.jpg' %}" alt="">

                   

                    </li>
                   </ul>
 
                </div>
            </div>
        
        </div>
       
        <div class="header_content">
           <div class="row">
                   <div class="header_content__right col-sm-7">
                  <ul class="nav">
                    <li class="nav-item">
                  <a class="nav-link" href="{% url 'home' %}">Home</a>
                   </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'Blogpost' %}">Blog</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'polls' %}">個人情報</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link " href="{% url 'contact' %}">ゲーム</a>
                </li>
            </ul>
           </div>
           <div class="header_content__left col-sm-5">
                  {% if user.username %}
                     <ul class="nav">
                        <li class="nav-item">                        
                             <a class="nav-link">Hello {{user.username}}</a>
                        </li>
                         <li class="nav-item">
                             <a class="nav-link"href="{% url 'logout' %}">ログアウト</a>
                         </li>
                    </ul>              
                {% else %}
                    <ul class="nav">
                        <li class="nav-item">
                             <a class="nav-link" href="{%  url 'register' %}">登録</a>
                        </li>
                         <li class="nav-item">
                             <a class="nav-link" href="{%  url 'login' %}">ログイン</a>
                         </li>
                    </ul>               
                {% endif %}
           </div>  
           </div>
                
        </div>
       
        <div class="header_logo">
            <img src="{% static './images/IMG_1216.JPG' %}"class="rounded-circle" width="110px" alt="">
          
        </div>


    </header>
     <div>
             {% block content %}
             {% endblock %}
    </div>
   <footer>
   　 
         <h1>江戸川大学 ３年生　グエンタントゥ　1932802　</h1>
   　
　　</footer>
   
</body>
</html>

mysite/polls/templates/pages/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
</head>
<body> 
     <form method="POST">
        {% csrf_token %}
        {% for key, value in form.errors.items %}
            {{value}}
        {% endfor %}
        <p><label>username:</label>{{form.username}}</p>
        <p><label>password:</label>{{form.password}}</p>
        <input type="hidden" name="next" value="/polls"/>
        <input type="submit" value="Login"/>
    </form>

    
</body>
</html>

mysite/polls/templates/pages/polls.html
 {% extends "pages/index.html" %}
{% load static %}
{% block title %}
Home
{% endblock %}

{% block content %}
<div class="row" style="margin:3%">
  <div class="col-sm-6">
    <p>氏名 : グエン　タントゥ</p>
    <p>就学種別　：	留学生</p>
    <p>大学名：江戸川大学</p>
    <p>所属学科組織　：	大学 メディア学部 情報文化学科</p>
    <p>学年	: 3年生</p>
  </div>
  <div class="col-sm-6">
      <img src="{% static './images/edogawa.jpg' %}"alt="" style="width:100%;" >
   </div>
</div>

 {% comment %} {% for comment in Commenttt_list %}
         <h4><strong>{{comment.author}}</strong></h4>
            <h6><p>{{comment.date}}</p></h6>
            <p>{{comment.body|linebreaks}}</p>
 {% endfor %} 
 {% if user.username %}
          <form  method="POST">
                {% csrf_token %}
                <p><label>コメント:</label></p>
                {{form.body}}
                <br/>
                <input type="submit" value="投稿"/>
{% endif %} {% endcomment %}
{% endblock %} 

mysite/polls/templates/pages/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
    　　アカウント登録をお願いいたします。
        <form action="." method="POST">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value="登録"/>
        </form>
    </center>
</body>
</html>